version: '3'
services:
  # mariadb:
  #  image: mariadb:${MARIADB_VERSION}
  #  container_name: mariadb
  #  restart: always
  #  volumes:
  #    - "${DATA_DIR}/mysql:/var/lib/mysql"
  #  environment: 
  #    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  # redis:
  #  image: redis:${REDIS_VERSION}
  #  restart: always

  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
    restart: always
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
      - "${DATA_DIR}/mysql:/var/lib/mysql"
    # links:
      # - mariadb:mariadb
      # - redis:redis
    environment:
      SQLITE_DATABASE: nextcloud
      # Very low RAM VM = can't use a MySQL db
      # MYSQL_HOST: mariadb
      # MYSQL_DATABASE: nextcloud
      # MYSQL_USER: root
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      NEXTCLOUD_ADMIN_USER: ${ADMIN_USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # REDIS_HOST: redis
    # depends_on:
      # - mariadb
      # - redis

  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs:ro"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - ./nginx.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - reverse-proxy

#  backups:
#    image: christophetd/duplicacy-autobackup:v1.0
#    container_name: backups
#    restart: always
#    environment:
#      BACKUP_NAME: "${BACKUP_NAME}"
#      BACKUP_LOCATION: ""
#      BACKUP_SCHEDULE: "${BACKUP_SCHEDULE}"
#      BACKUP_ENCRYPTION_KEY: "${BACKUP_ENCRYPTION_KEY}"
#      B2_ID: "${B2_ID}"
#      HUBIC_TOKEN_FILE: "${HUBIC_TOKEN_FILE}"
#    volumes:
#      - "${DATA_DIR}:/data"

#  adminer:
#    image: adminer
#    restart: always
#    environment:
#      LETSENCRYPT_HOST: ${ADMINER_HOST}
#      VIRTUAL_PORT: 8080
#      VIRTUAL_HOST: ${ADMINER_HOST}
#      LETSENCRYPT_EMAIL: #{LETSENCRYPT_EMAIL}
#    depends_on:
#      - mariadb
